/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ComandaDAO;
import model.Comanda;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Objects;

public class MenuRestaurante extends javax.swing.JFrame {

    private int comandaAtualId = -1;
    
    public MenuRestaurante() {
        initComponents();
        atualizarStatus();
        configurarBotoes();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovaComanda = new javax.swing.JButton();
        btnAdicionarItem = new javax.swing.JButton();
        btnVisualizarComanda = new javax.swing.JButton();
        btnGerarRecibo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNovaComanda.setText("Nova Comanda");

        btnAdicionarItem.setText("Adicionar Item");
        btnAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItemActionPerformed(evt);
            }
        });

        btnVisualizarComanda.setText("Visualizar Comanda");

        btnGerarRecibo.setText("Gerar Recibo");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SISTEMA RESTAURANTE");

        lblStatus.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNovaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVisualizarComanda)
                            .addComponent(btnGerarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(btnNovaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnAdicionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnVisualizarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnGerarRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarItemActionPerformed

    private void configurarBotoes() {
        btnNovaComanda.addActionListener(e -> criarNovaComanda());
        btnAdicionarItem.addActionListener(e -> abrirAdicionarItem());
        btnVisualizarComanda.addActionListener(e -> abrirVisualizarComanda());
        btnGerarRecibo.addActionListener(e -> abrirGerarRecibo());
    }

    private void criarNovaComanda() {
        ComandaDAO comandaDAO = new ComandaDAO();
        comandaAtualId = comandaDAO.criarComanda();
        if (comandaAtualId != -1) {
            JOptionPane.showMessageDialog(this, "Nova comanda criada com ID: " + comandaAtualId);
            atualizarStatus();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao criar comanda!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void abrirAdicionarItem() {
        SelecionarComanda selecionar = new SelecionarComanda();
        selecionar.setVisible(true);
        selecionar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                Comanda selecionada = selecionar.getComandaSelecionada();
                if (selecionada != null) {
                    comandaAtualId = selecionada.getId();
                    atualizarStatus();
                    new AdicionarItem(MenuRestaurante.this, comandaAtualId).setVisible(true);
                }
            }
        });
    }

    private void abrirVisualizarComanda() {
        SelecionarComanda selecionar = new SelecionarComanda();
        selecionar.setVisible(true);
        selecionar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                Comanda selecionada = selecionar.getComandaSelecionada();
                if (selecionada != null) {
                    comandaAtualId = selecionada.getId();
                    atualizarStatus();
                    new VisualizarComanda(comandaAtualId).setVisible(true);
                }
            }
        });
    }

    private void abrirGerarRecibo() {
        SelecionarComanda selecionar = new SelecionarComanda();
        selecionar.setVisible(true);
        selecionar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                Comanda selecionada = selecionar.getComandaSelecionada();
                if (selecionada != null) {
                    comandaAtualId = selecionar.getComandaSelecionada().getId();
                    atualizarStatus();
                    new GerarRecibo(comandaAtualId).setVisible(true);
                }
            }
        });
    }

    private void atualizarStatus() {
        if (comandaAtualId == -1) {
            lblStatus.setText("Nenhuma comanda aberta");
        } else {
            lblStatus.setText("Comanda atual: #" + comandaAtualId);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarItem;
    private javax.swing.JButton btnGerarRecibo;
    private javax.swing.JButton btnNovaComanda;
    private javax.swing.JButton btnVisualizarComanda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
